[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pymars"
description = "Pure Python Earth (MARS) algorithm"
readme = "README.md"
authors = [{name = "pymars developers"}]
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "numpy",
    "scikit-learn",
]

[project.urls]
Homepage = "https://github.com/pymars/pymars"

[project.entry-points.console_scripts]
pymars = "pymars.cli:main"



[tool.setuptools]
packages = ["pymars"]
package-dir = {"" = "."}

[tool.setuptools.dynamic]
version = {attr = "pymars.__version__"}
